#!/bin/bash

source $(dirname $0)/slinky.cfg

echo -e "\e[31;1mThis command will uninstall Slinky and remove any links that you have created."
read -r -p $'\e[36;1mAre you sure you want to do this? \e[0m\e[33m[y/N]\e[0m : ' response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
  delete_files=('slink' 'rmslink' 'lsslink' 'delslink'  'slinky-run.sh' 'relativepath.sh' 'slinky.cfg')
  for file in "${delete_files[@]}"; do
    echo "Deleting $(dirname $0)/$file"
    rm "$(dirname $0)/$file"
  done
  echo "Deleting $install_dir/"
  rm -r $install_dir
  echo "Slinky has been uninstalled successfully"
fi

