#!/bin/bash

source $(dirname $0)/slinky.cfg

echo "This command will uninstall Slinky and remove any links that you have created."
read -r -p "Are you sure you want to do this? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
  delete_files=('slink' 'rmslink' 'lsslink' 'delslink'  'slinky-run.sh' 'relativepath.sh' 'slinky.cfg')
  for file in "${delete_files[@]}"; do
    echo $run_file
    file_path = "$(dirname $run_file)/$file"
    echo "Deleting $file_path"
    rm "$file_path"
  done
  echo "Deleting $install_dir/"
  rm -r $install_dir
  echo "Slinky has been uninstalled successfully"
fi

