#!/bin/bash

source $(dirname $0)/slinky.cfg

for filename in $install_dir/*.bat; do
  # second line in the file contains the command name after 'rem '
  command_line=$(tail -n+2 $filename | head -n1)
  linux_name=${command_line#'rem '}
  echo "$filename ---> $linux_name"
done

