#!/bin/bash

source $(dirname $0)/slinky.cfg

if [ $# -lt 1 ]
then
  echo "Usage: rmslink [win command]"
  echo ""
  echo "Remove the link between [win command] and a Bash for Windows command."
  exit 1
fi

filename="$install_dir/$1.bat"

command_line=$(tail -n+2 $filename | head -n1)
linux_name=${command_line#'rem '}

rm "$filename"

echo "$filename -/-> $linux_name"
